language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
services:
  - mongodb
script:
  - rm -rf package-lock.json node_modules 
  - yarn install
  - yarn install coveralls
  - yarn test